steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - fetch_data_option3_cf
  - --source=.
  - --trigger-http
  - --runtime=python39
  - --allow-unauthenticated
  - --set-env-vars=PIP_CONFIG_FILE=requirements.txt
